### PR TITLE
Ensure vim always runs from a shell

### PR DESCRIPTION
**Pull request by iamjarvo**
Allows MacVim to use the correct ruby version

### CODE REVIEW

**Comment by iamjarvo** [comment]
Please double check this. I don't have a good way of testing.

**Comment by jgarber** [comment]
:+1: Didn't break anything for me, but I also don't understand what it's for. I can `:!date` successfully both when I start MacVim from a shell and when I don't.

**Comment by iamjarvo** [comment]
@jgarber it allows macvim to recognize the ruby version in your shell. The problem it solves is macvim using system ruby and not having updated syntax with 2.2.2

**Comment by nicholaides** [comment]
Cool. What would a test case look like?

**Comment by iamjarvo** [comment]
@nicholaides when you open macvim use the keyword argument syntax with an empty value so `def say_hi(name:)` and your syntax highlighting should show an error. With this change and your ruby version set to to 2.2.x you should not see the error.

**Pull request merged**
